services:
  telegram_media_downloader:
    image: roninriddle/telegram_media_downloader:0.0.6
    container_name: telegram_media_downloader
    ports:
      - "5055:5000"
    environment:
      TMD_CONFIG_FILE: /config/config.yaml
      TMD_DATA_FILE: /config/data.yaml
      TMD_SAVE_PATH: /app/downloads
      TMD_TEMP_PATH: /app/temp
      TMD_LOG_PATH: /app/log
      TMD_SESSION_PATH: /app/sessions
      TMD_TASK_HISTORY_FILE: /config/task_history.json
      TZ: Asia/Shanghai
    volumes:
      - ./config:/config
      - ./app:/app
    restart: unless-stopped
